// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: festival.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from festival.proto</summary>
public static partial class FestivalReflection {

  #region Descriptor
  /// <summary>File descriptor for festival.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FestivalReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5mZXN0aXZhbC5wcm90byJZCg1Mb2dJblJlc3BvbnNlEg0KBXRva2VuGAEg",
          "ASgJEg0KBWVycm9yGAIgASgJEg8KB3N1Y2Nlc3MYAyABKAgSGQoHYW5nYWph",
          "dBgEIAEoCzIILkFuZ2FqYXQiKgoHQW5nYWphdBINCgV0b2tlbhgBIAEoCRIQ",
          "CghwYXNzd29yZBgCIAEoCSIyCg1TdHJlYW1SZXF1ZXN0EhIKCmFuZ2FqYXRf",
          "aWQYASABKAkSDQoFdG9rZW4YAiABKAkihAEKDFNwZWN0YWNvbERUTxIPCgds",
          "b2NhdGllGAEgASgJEg8KB2lkX3NwZWMYAiABKAkSDAoEZGF0YRgDIAEoCRIO",
          "CgZhcnRpc3QYBCABKAkSFwoPbnJMb2N1cmlWYW5kdXRlGAUgASgJEhsKE25y",
          "TG9jdXJpRGlzcG9uaWJpbGUYBiABKAkiXgoFQmlsZXQSEQoJbnVtZV9jdW1w",
          "GAEgASgJEiAKCXNwZWN0YWNvbBgCIAEoCzINLlNwZWN0YWNvbERUTxINCgVz",
          "ZXJpZRgDIAEoCRIRCglucl9sb2N1cmkYBCABKAkinwIKD0Zlc3RpdmFsUmVx",
          "dWVzdBIxCgtyZXF1ZXN0VHlwZRgBIAEoDjIcLkZlc3RpdmFsUmVxdWVzdC5S",
          "ZXF1ZXN0VHlwZRIbCgdhbmdhamF0GAIgASgLMgguQW5nYWphdEgAEiIKCXNw",
          "ZWN0YWNvbBgDIAEoCzINLlNwZWN0YWNvbERUT0gAEhcKBWJpbGV0GAQgASgL",
          "MgYuQmlsZXRIABIYCg5maWx0ZXJlZEJ5RGF0ZRgFIAEoCEgAIloKC1JlcXVl",
          "c3RUeXBlEgkKBUxPR0lOEAASCgoGTE9HT1VUEAESDwoLU0VMTF9USUNLRVQQ",
          "AhISCg5HRVRfU1BFQ1RBQ09MRRADEg8KC0dFVF9BUlRJU1RJEARCCQoHcGF5",
          "bG9hZCK1AwoQRmVzdGl2YWxSZXNwb25zZRIVCgViaWxldBgIIAEoCzIGLkJp",
          "bGV0EjQKDHJlc3BvbnNlVHlwZRgBIAEoDjIeLkZlc3RpdmFsUmVzcG9uc2Uu",
          "UmVzcG9uc2VUeXBlEiAKCXNwZWN0YWNvbBgCIAEoCzINLlNwZWN0YWNvbERU",
          "TxIPCgdtZXNzYWdlGAYgASgJEiEKCnNwZWN0YWNvbGUYAyADKAsyDS5TcGVj",
          "dGFjb2xEVE8SDQoFZXJyb3IYBCABKAkSDgoGYXJ0aXN0GAUgAygJEhkKB2Fu",
          "Z2FqYXQYByABKAsyCC5BbmdhamF0EhYKDmZpbHRlcmVkQnlEYXRlGAkgASgI",
          "IqsBCgxSZXNwb25zZVR5cGUSBgoCT0sQABIJCgVFUlJPUhABEhgKFEdPVF9G",
          "RVNUSVZBTF9VUERBVEVEEAISFQoRR0VUX0ZFU1RJVkFMX0xJU1QQAxIdChlH",
          "T1RfRkVTVElWQUxfTElTVF9VUERBVEVEEAQSEgoOVVNFUl9MT0dHRURfSU4Q",
          "BRITCg9VU0VSX0xPR0dFRF9PVVQQBhIPCgtHRVRfQVJUSVNUSRAHQhEKAEIN",
          "RmVzdGl2YWxQcm90b2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::LogInResponse), global::LogInResponse.Parser, new[]{ "Token", "Error", "Success", "Angajat" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Angajat), global::Angajat.Parser, new[]{ "Token", "Password" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::StreamRequest), global::StreamRequest.Parser, new[]{ "AngajatId", "Token" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SpectacolDTO), global::SpectacolDTO.Parser, new[]{ "Locatie", "IdSpec", "Data", "Artist", "NrLocuriVandute", "NrLocuriDisponibile" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Bilet), global::Bilet.Parser, new[]{ "NumeCump", "Spectacol", "Serie", "NrLocuri" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FestivalRequest), global::FestivalRequest.Parser, new[]{ "RequestType", "Angajat", "Spectacol", "Bilet", "FilteredByDate" }, new[]{ "Payload" }, new[]{ typeof(global::FestivalRequest.Types.RequestType) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FestivalResponse), global::FestivalResponse.Parser, new[]{ "Bilet", "ResponseType", "Spectacol", "Message", "Spectacole", "Error", "Artist", "Angajat", "FilteredByDate" }, null, new[]{ typeof(global::FestivalResponse.Types.ResponseType) }, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LogInResponse : pb::IMessage<LogInResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LogInResponse> _parser = new pb::MessageParser<LogInResponse>(() => new LogInResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LogInResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FestivalReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LogInResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LogInResponse(LogInResponse other) : this() {
    token_ = other.token_;
    error_ = other.error_;
    success_ = other.success_;
    angajat_ = other.angajat_ != null ? other.angajat_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LogInResponse Clone() {
    return new LogInResponse(this);
  }

  /// <summary>Field number for the "token" field.</summary>
  public const int TokenFieldNumber = 1;
  private string token_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Token {
    get { return token_; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 2;
  private string error_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Error {
    get { return error_; }
    set {
      error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "success" field.</summary>
  public const int SuccessFieldNumber = 3;
  private bool success_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Success {
    get { return success_; }
    set {
      success_ = value;
    }
  }

  /// <summary>Field number for the "angajat" field.</summary>
  public const int AngajatFieldNumber = 4;
  private global::Angajat angajat_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Angajat Angajat {
    get { return angajat_; }
    set {
      angajat_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LogInResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LogInResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Token != other.Token) return false;
    if (Error != other.Error) return false;
    if (Success != other.Success) return false;
    if (!object.Equals(Angajat, other.Angajat)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Token.Length != 0) hash ^= Token.GetHashCode();
    if (Error.Length != 0) hash ^= Error.GetHashCode();
    if (Success != false) hash ^= Success.GetHashCode();
    if (angajat_ != null) hash ^= Angajat.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Token.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Token);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Error);
    }
    if (Success != false) {
      output.WriteRawTag(24);
      output.WriteBool(Success);
    }
    if (angajat_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Angajat);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Token.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Token);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Error);
    }
    if (Success != false) {
      output.WriteRawTag(24);
      output.WriteBool(Success);
    }
    if (angajat_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Angajat);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Token.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
    }
    if (Error.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
    }
    if (Success != false) {
      size += 1 + 1;
    }
    if (angajat_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LogInResponse other) {
    if (other == null) {
      return;
    }
    if (other.Token.Length != 0) {
      Token = other.Token;
    }
    if (other.Error.Length != 0) {
      Error = other.Error;
    }
    if (other.Success != false) {
      Success = other.Success;
    }
    if (other.angajat_ != null) {
      if (angajat_ == null) {
        Angajat = new global::Angajat();
      }
      Angajat.MergeFrom(other.Angajat);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Token = input.ReadString();
          break;
        }
        case 18: {
          Error = input.ReadString();
          break;
        }
        case 24: {
          Success = input.ReadBool();
          break;
        }
        case 34: {
          if (angajat_ == null) {
            Angajat = new global::Angajat();
          }
          input.ReadMessage(Angajat);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Token = input.ReadString();
          break;
        }
        case 18: {
          Error = input.ReadString();
          break;
        }
        case 24: {
          Success = input.ReadBool();
          break;
        }
        case 34: {
          if (angajat_ == null) {
            Angajat = new global::Angajat();
          }
          input.ReadMessage(Angajat);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Angajat : pb::IMessage<Angajat>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Angajat> _parser = new pb::MessageParser<Angajat>(() => new Angajat());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Angajat> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FestivalReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Angajat() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Angajat(Angajat other) : this() {
    token_ = other.token_;
    password_ = other.password_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Angajat Clone() {
    return new Angajat(this);
  }

  /// <summary>Field number for the "token" field.</summary>
  public const int TokenFieldNumber = 1;
  private string token_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Token {
    get { return token_; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 2;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Angajat);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Angajat other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Token != other.Token) return false;
    if (Password != other.Password) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Token.Length != 0) hash ^= Token.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Token.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Token);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Token.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Token);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Token.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Angajat other) {
    if (other == null) {
      return;
    }
    if (other.Token.Length != 0) {
      Token = other.Token;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Token = input.ReadString();
          break;
        }
        case 18: {
          Password = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Token = input.ReadString();
          break;
        }
        case 18: {
          Password = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class StreamRequest : pb::IMessage<StreamRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<StreamRequest> _parser = new pb::MessageParser<StreamRequest>(() => new StreamRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<StreamRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FestivalReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public StreamRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public StreamRequest(StreamRequest other) : this() {
    angajatId_ = other.angajatId_;
    token_ = other.token_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public StreamRequest Clone() {
    return new StreamRequest(this);
  }

  /// <summary>Field number for the "angajat_id" field.</summary>
  public const int AngajatIdFieldNumber = 1;
  private string angajatId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AngajatId {
    get { return angajatId_; }
    set {
      angajatId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "token" field.</summary>
  public const int TokenFieldNumber = 2;
  private string token_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Token {
    get { return token_; }
    set {
      token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as StreamRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(StreamRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (AngajatId != other.AngajatId) return false;
    if (Token != other.Token) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (AngajatId.Length != 0) hash ^= AngajatId.GetHashCode();
    if (Token.Length != 0) hash ^= Token.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (AngajatId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(AngajatId);
    }
    if (Token.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Token);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (AngajatId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(AngajatId);
    }
    if (Token.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Token);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (AngajatId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AngajatId);
    }
    if (Token.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(StreamRequest other) {
    if (other == null) {
      return;
    }
    if (other.AngajatId.Length != 0) {
      AngajatId = other.AngajatId;
    }
    if (other.Token.Length != 0) {
      Token = other.Token;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          AngajatId = input.ReadString();
          break;
        }
        case 18: {
          Token = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          AngajatId = input.ReadString();
          break;
        }
        case 18: {
          Token = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class SpectacolDTO : pb::IMessage<SpectacolDTO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SpectacolDTO> _parser = new pb::MessageParser<SpectacolDTO>(() => new SpectacolDTO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SpectacolDTO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FestivalReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SpectacolDTO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SpectacolDTO(SpectacolDTO other) : this() {
    locatie_ = other.locatie_;
    idSpec_ = other.idSpec_;
    data_ = other.data_;
    artist_ = other.artist_;
    nrLocuriVandute_ = other.nrLocuriVandute_;
    nrLocuriDisponibile_ = other.nrLocuriDisponibile_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SpectacolDTO Clone() {
    return new SpectacolDTO(this);
  }

  /// <summary>Field number for the "locatie" field.</summary>
  public const int LocatieFieldNumber = 1;
  private string locatie_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Locatie {
    get { return locatie_; }
    set {
      locatie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "id_spec" field.</summary>
  public const int IdSpecFieldNumber = 2;
  private string idSpec_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string IdSpec {
    get { return idSpec_; }
    set {
      idSpec_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 3;
  private string data_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Data {
    get { return data_; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "artist" field.</summary>
  public const int ArtistFieldNumber = 4;
  private string artist_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Artist {
    get { return artist_; }
    set {
      artist_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "nrLocuriVandute" field.</summary>
  public const int NrLocuriVanduteFieldNumber = 5;
  private string nrLocuriVandute_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NrLocuriVandute {
    get { return nrLocuriVandute_; }
    set {
      nrLocuriVandute_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "nrLocuriDisponibile" field.</summary>
  public const int NrLocuriDisponibileFieldNumber = 6;
  private string nrLocuriDisponibile_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NrLocuriDisponibile {
    get { return nrLocuriDisponibile_; }
    set {
      nrLocuriDisponibile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SpectacolDTO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SpectacolDTO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Locatie != other.Locatie) return false;
    if (IdSpec != other.IdSpec) return false;
    if (Data != other.Data) return false;
    if (Artist != other.Artist) return false;
    if (NrLocuriVandute != other.NrLocuriVandute) return false;
    if (NrLocuriDisponibile != other.NrLocuriDisponibile) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Locatie.Length != 0) hash ^= Locatie.GetHashCode();
    if (IdSpec.Length != 0) hash ^= IdSpec.GetHashCode();
    if (Data.Length != 0) hash ^= Data.GetHashCode();
    if (Artist.Length != 0) hash ^= Artist.GetHashCode();
    if (NrLocuriVandute.Length != 0) hash ^= NrLocuriVandute.GetHashCode();
    if (NrLocuriDisponibile.Length != 0) hash ^= NrLocuriDisponibile.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Locatie.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Locatie);
    }
    if (IdSpec.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(IdSpec);
    }
    if (Data.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Data);
    }
    if (Artist.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Artist);
    }
    if (NrLocuriVandute.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(NrLocuriVandute);
    }
    if (NrLocuriDisponibile.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(NrLocuriDisponibile);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Locatie.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Locatie);
    }
    if (IdSpec.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(IdSpec);
    }
    if (Data.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Data);
    }
    if (Artist.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Artist);
    }
    if (NrLocuriVandute.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(NrLocuriVandute);
    }
    if (NrLocuriDisponibile.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(NrLocuriDisponibile);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Locatie.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Locatie);
    }
    if (IdSpec.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(IdSpec);
    }
    if (Data.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
    }
    if (Artist.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Artist);
    }
    if (NrLocuriVandute.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NrLocuriVandute);
    }
    if (NrLocuriDisponibile.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NrLocuriDisponibile);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SpectacolDTO other) {
    if (other == null) {
      return;
    }
    if (other.Locatie.Length != 0) {
      Locatie = other.Locatie;
    }
    if (other.IdSpec.Length != 0) {
      IdSpec = other.IdSpec;
    }
    if (other.Data.Length != 0) {
      Data = other.Data;
    }
    if (other.Artist.Length != 0) {
      Artist = other.Artist;
    }
    if (other.NrLocuriVandute.Length != 0) {
      NrLocuriVandute = other.NrLocuriVandute;
    }
    if (other.NrLocuriDisponibile.Length != 0) {
      NrLocuriDisponibile = other.NrLocuriDisponibile;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Locatie = input.ReadString();
          break;
        }
        case 18: {
          IdSpec = input.ReadString();
          break;
        }
        case 26: {
          Data = input.ReadString();
          break;
        }
        case 34: {
          Artist = input.ReadString();
          break;
        }
        case 42: {
          NrLocuriVandute = input.ReadString();
          break;
        }
        case 50: {
          NrLocuriDisponibile = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Locatie = input.ReadString();
          break;
        }
        case 18: {
          IdSpec = input.ReadString();
          break;
        }
        case 26: {
          Data = input.ReadString();
          break;
        }
        case 34: {
          Artist = input.ReadString();
          break;
        }
        case 42: {
          NrLocuriVandute = input.ReadString();
          break;
        }
        case 50: {
          NrLocuriDisponibile = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Bilet : pb::IMessage<Bilet>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Bilet> _parser = new pb::MessageParser<Bilet>(() => new Bilet());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Bilet> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FestivalReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Bilet() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Bilet(Bilet other) : this() {
    numeCump_ = other.numeCump_;
    spectacol_ = other.spectacol_ != null ? other.spectacol_.Clone() : null;
    serie_ = other.serie_;
    nrLocuri_ = other.nrLocuri_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Bilet Clone() {
    return new Bilet(this);
  }

  /// <summary>Field number for the "nume_cump" field.</summary>
  public const int NumeCumpFieldNumber = 1;
  private string numeCump_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NumeCump {
    get { return numeCump_; }
    set {
      numeCump_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "spectacol" field.</summary>
  public const int SpectacolFieldNumber = 2;
  private global::SpectacolDTO spectacol_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SpectacolDTO Spectacol {
    get { return spectacol_; }
    set {
      spectacol_ = value;
    }
  }

  /// <summary>Field number for the "serie" field.</summary>
  public const int SerieFieldNumber = 3;
  private string serie_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Serie {
    get { return serie_; }
    set {
      serie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "nr_locuri" field.</summary>
  public const int NrLocuriFieldNumber = 4;
  private string nrLocuri_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NrLocuri {
    get { return nrLocuri_; }
    set {
      nrLocuri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Bilet);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Bilet other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (NumeCump != other.NumeCump) return false;
    if (!object.Equals(Spectacol, other.Spectacol)) return false;
    if (Serie != other.Serie) return false;
    if (NrLocuri != other.NrLocuri) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (NumeCump.Length != 0) hash ^= NumeCump.GetHashCode();
    if (spectacol_ != null) hash ^= Spectacol.GetHashCode();
    if (Serie.Length != 0) hash ^= Serie.GetHashCode();
    if (NrLocuri.Length != 0) hash ^= NrLocuri.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (NumeCump.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(NumeCump);
    }
    if (spectacol_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Spectacol);
    }
    if (Serie.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Serie);
    }
    if (NrLocuri.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(NrLocuri);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (NumeCump.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(NumeCump);
    }
    if (spectacol_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Spectacol);
    }
    if (Serie.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Serie);
    }
    if (NrLocuri.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(NrLocuri);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (NumeCump.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeCump);
    }
    if (spectacol_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spectacol);
    }
    if (Serie.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Serie);
    }
    if (NrLocuri.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NrLocuri);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Bilet other) {
    if (other == null) {
      return;
    }
    if (other.NumeCump.Length != 0) {
      NumeCump = other.NumeCump;
    }
    if (other.spectacol_ != null) {
      if (spectacol_ == null) {
        Spectacol = new global::SpectacolDTO();
      }
      Spectacol.MergeFrom(other.Spectacol);
    }
    if (other.Serie.Length != 0) {
      Serie = other.Serie;
    }
    if (other.NrLocuri.Length != 0) {
      NrLocuri = other.NrLocuri;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          NumeCump = input.ReadString();
          break;
        }
        case 18: {
          if (spectacol_ == null) {
            Spectacol = new global::SpectacolDTO();
          }
          input.ReadMessage(Spectacol);
          break;
        }
        case 26: {
          Serie = input.ReadString();
          break;
        }
        case 34: {
          NrLocuri = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          NumeCump = input.ReadString();
          break;
        }
        case 18: {
          if (spectacol_ == null) {
            Spectacol = new global::SpectacolDTO();
          }
          input.ReadMessage(Spectacol);
          break;
        }
        case 26: {
          Serie = input.ReadString();
          break;
        }
        case 34: {
          NrLocuri = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class FestivalRequest : pb::IMessage<FestivalRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FestivalRequest> _parser = new pb::MessageParser<FestivalRequest>(() => new FestivalRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FestivalRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FestivalReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FestivalRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FestivalRequest(FestivalRequest other) : this() {
    requestType_ = other.requestType_;
    switch (other.PayloadCase) {
      case PayloadOneofCase.Angajat:
        Angajat = other.Angajat.Clone();
        break;
      case PayloadOneofCase.Spectacol:
        Spectacol = other.Spectacol.Clone();
        break;
      case PayloadOneofCase.Bilet:
        Bilet = other.Bilet.Clone();
        break;
      case PayloadOneofCase.FilteredByDate:
        FilteredByDate = other.FilteredByDate;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FestivalRequest Clone() {
    return new FestivalRequest(this);
  }

  /// <summary>Field number for the "requestType" field.</summary>
  public const int RequestTypeFieldNumber = 1;
  private global::FestivalRequest.Types.RequestType requestType_ = global::FestivalRequest.Types.RequestType.Login;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::FestivalRequest.Types.RequestType RequestType {
    get { return requestType_; }
    set {
      requestType_ = value;
    }
  }

  /// <summary>Field number for the "angajat" field.</summary>
  public const int AngajatFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Angajat Angajat {
    get { return payloadCase_ == PayloadOneofCase.Angajat ? (global::Angajat) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Angajat;
    }
  }

  /// <summary>Field number for the "spectacol" field.</summary>
  public const int SpectacolFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SpectacolDTO Spectacol {
    get { return payloadCase_ == PayloadOneofCase.Spectacol ? (global::SpectacolDTO) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Spectacol;
    }
  }

  /// <summary>Field number for the "bilet" field.</summary>
  public const int BiletFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Bilet Bilet {
    get { return payloadCase_ == PayloadOneofCase.Bilet ? (global::Bilet) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Bilet;
    }
  }

  /// <summary>Field number for the "filteredByDate" field.</summary>
  public const int FilteredByDateFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool FilteredByDate {
    get { return HasFilteredByDate ? (bool) payload_ : false; }
    set {
      payload_ = value;
      payloadCase_ = PayloadOneofCase.FilteredByDate;
    }
  }
  /// <summary>Gets whether the "filteredByDate" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasFilteredByDate {
    get { return payloadCase_ == PayloadOneofCase.FilteredByDate; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "filteredByDate" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearFilteredByDate() {
    if (HasFilteredByDate) {
      ClearPayload();
    }
  }

  private object payload_;
  /// <summary>Enum of possible cases for the "payload" oneof.</summary>
  public enum PayloadOneofCase {
    None = 0,
    Angajat = 2,
    Spectacol = 3,
    Bilet = 4,
    FilteredByDate = 5,
  }
  private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PayloadOneofCase PayloadCase {
    get { return payloadCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayload() {
    payloadCase_ = PayloadOneofCase.None;
    payload_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FestivalRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FestivalRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RequestType != other.RequestType) return false;
    if (!object.Equals(Angajat, other.Angajat)) return false;
    if (!object.Equals(Spectacol, other.Spectacol)) return false;
    if (!object.Equals(Bilet, other.Bilet)) return false;
    if (FilteredByDate != other.FilteredByDate) return false;
    if (PayloadCase != other.PayloadCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RequestType != global::FestivalRequest.Types.RequestType.Login) hash ^= RequestType.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Angajat) hash ^= Angajat.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Spectacol) hash ^= Spectacol.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Bilet) hash ^= Bilet.GetHashCode();
    if (HasFilteredByDate) hash ^= FilteredByDate.GetHashCode();
    hash ^= (int) payloadCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RequestType != global::FestivalRequest.Types.RequestType.Login) {
      output.WriteRawTag(8);
      output.WriteEnum((int) RequestType);
    }
    if (payloadCase_ == PayloadOneofCase.Angajat) {
      output.WriteRawTag(18);
      output.WriteMessage(Angajat);
    }
    if (payloadCase_ == PayloadOneofCase.Spectacol) {
      output.WriteRawTag(26);
      output.WriteMessage(Spectacol);
    }
    if (payloadCase_ == PayloadOneofCase.Bilet) {
      output.WriteRawTag(34);
      output.WriteMessage(Bilet);
    }
    if (HasFilteredByDate) {
      output.WriteRawTag(40);
      output.WriteBool(FilteredByDate);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RequestType != global::FestivalRequest.Types.RequestType.Login) {
      output.WriteRawTag(8);
      output.WriteEnum((int) RequestType);
    }
    if (payloadCase_ == PayloadOneofCase.Angajat) {
      output.WriteRawTag(18);
      output.WriteMessage(Angajat);
    }
    if (payloadCase_ == PayloadOneofCase.Spectacol) {
      output.WriteRawTag(26);
      output.WriteMessage(Spectacol);
    }
    if (payloadCase_ == PayloadOneofCase.Bilet) {
      output.WriteRawTag(34);
      output.WriteMessage(Bilet);
    }
    if (HasFilteredByDate) {
      output.WriteRawTag(40);
      output.WriteBool(FilteredByDate);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RequestType != global::FestivalRequest.Types.RequestType.Login) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestType);
    }
    if (payloadCase_ == PayloadOneofCase.Angajat) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
    }
    if (payloadCase_ == PayloadOneofCase.Spectacol) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spectacol);
    }
    if (payloadCase_ == PayloadOneofCase.Bilet) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
    }
    if (HasFilteredByDate) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FestivalRequest other) {
    if (other == null) {
      return;
    }
    if (other.RequestType != global::FestivalRequest.Types.RequestType.Login) {
      RequestType = other.RequestType;
    }
    switch (other.PayloadCase) {
      case PayloadOneofCase.Angajat:
        if (Angajat == null) {
          Angajat = new global::Angajat();
        }
        Angajat.MergeFrom(other.Angajat);
        break;
      case PayloadOneofCase.Spectacol:
        if (Spectacol == null) {
          Spectacol = new global::SpectacolDTO();
        }
        Spectacol.MergeFrom(other.Spectacol);
        break;
      case PayloadOneofCase.Bilet:
        if (Bilet == null) {
          Bilet = new global::Bilet();
        }
        Bilet.MergeFrom(other.Bilet);
        break;
      case PayloadOneofCase.FilteredByDate:
        FilteredByDate = other.FilteredByDate;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RequestType = (global::FestivalRequest.Types.RequestType) input.ReadEnum();
          break;
        }
        case 18: {
          global::Angajat subBuilder = new global::Angajat();
          if (payloadCase_ == PayloadOneofCase.Angajat) {
            subBuilder.MergeFrom(Angajat);
          }
          input.ReadMessage(subBuilder);
          Angajat = subBuilder;
          break;
        }
        case 26: {
          global::SpectacolDTO subBuilder = new global::SpectacolDTO();
          if (payloadCase_ == PayloadOneofCase.Spectacol) {
            subBuilder.MergeFrom(Spectacol);
          }
          input.ReadMessage(subBuilder);
          Spectacol = subBuilder;
          break;
        }
        case 34: {
          global::Bilet subBuilder = new global::Bilet();
          if (payloadCase_ == PayloadOneofCase.Bilet) {
            subBuilder.MergeFrom(Bilet);
          }
          input.ReadMessage(subBuilder);
          Bilet = subBuilder;
          break;
        }
        case 40: {
          FilteredByDate = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          RequestType = (global::FestivalRequest.Types.RequestType) input.ReadEnum();
          break;
        }
        case 18: {
          global::Angajat subBuilder = new global::Angajat();
          if (payloadCase_ == PayloadOneofCase.Angajat) {
            subBuilder.MergeFrom(Angajat);
          }
          input.ReadMessage(subBuilder);
          Angajat = subBuilder;
          break;
        }
        case 26: {
          global::SpectacolDTO subBuilder = new global::SpectacolDTO();
          if (payloadCase_ == PayloadOneofCase.Spectacol) {
            subBuilder.MergeFrom(Spectacol);
          }
          input.ReadMessage(subBuilder);
          Spectacol = subBuilder;
          break;
        }
        case 34: {
          global::Bilet subBuilder = new global::Bilet();
          if (payloadCase_ == PayloadOneofCase.Bilet) {
            subBuilder.MergeFrom(Bilet);
          }
          input.ReadMessage(subBuilder);
          Bilet = subBuilder;
          break;
        }
        case 40: {
          FilteredByDate = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the FestivalRequest message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum RequestType {
      [pbr::OriginalName("LOGIN")] Login = 0,
      [pbr::OriginalName("LOGOUT")] Logout = 1,
      [pbr::OriginalName("SELL_TICKET")] SellTicket = 2,
      [pbr::OriginalName("GET_SPECTACOLE")] GetSpectacole = 3,
      [pbr::OriginalName("GET_ARTISTI")] GetArtisti = 4,
    }

  }
  #endregion

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class FestivalResponse : pb::IMessage<FestivalResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FestivalResponse> _parser = new pb::MessageParser<FestivalResponse>(() => new FestivalResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FestivalResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FestivalReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FestivalResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FestivalResponse(FestivalResponse other) : this() {
    bilet_ = other.bilet_ != null ? other.bilet_.Clone() : null;
    responseType_ = other.responseType_;
    spectacol_ = other.spectacol_ != null ? other.spectacol_.Clone() : null;
    message_ = other.message_;
    spectacole_ = other.spectacole_.Clone();
    error_ = other.error_;
    artist_ = other.artist_.Clone();
    angajat_ = other.angajat_ != null ? other.angajat_.Clone() : null;
    filteredByDate_ = other.filteredByDate_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FestivalResponse Clone() {
    return new FestivalResponse(this);
  }

  /// <summary>Field number for the "bilet" field.</summary>
  public const int BiletFieldNumber = 8;
  private global::Bilet bilet_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Bilet Bilet {
    get { return bilet_; }
    set {
      bilet_ = value;
    }
  }

  /// <summary>Field number for the "responseType" field.</summary>
  public const int ResponseTypeFieldNumber = 1;
  private global::FestivalResponse.Types.ResponseType responseType_ = global::FestivalResponse.Types.ResponseType.Ok;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::FestivalResponse.Types.ResponseType ResponseType {
    get { return responseType_; }
    set {
      responseType_ = value;
    }
  }

  /// <summary>Field number for the "spectacol" field.</summary>
  public const int SpectacolFieldNumber = 2;
  private global::SpectacolDTO spectacol_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SpectacolDTO Spectacol {
    get { return spectacol_; }
    set {
      spectacol_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 6;
  private string message_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "spectacole" field.</summary>
  public const int SpectacoleFieldNumber = 3;
  private static readonly pb::FieldCodec<global::SpectacolDTO> _repeated_spectacole_codec
      = pb::FieldCodec.ForMessage(26, global::SpectacolDTO.Parser);
  private readonly pbc::RepeatedField<global::SpectacolDTO> spectacole_ = new pbc::RepeatedField<global::SpectacolDTO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::SpectacolDTO> Spectacole {
    get { return spectacole_; }
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 4;
  private string error_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Error {
    get { return error_; }
    set {
      error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "artist" field.</summary>
  public const int ArtistFieldNumber = 5;
  private static readonly pb::FieldCodec<string> _repeated_artist_codec
      = pb::FieldCodec.ForString(42);
  private readonly pbc::RepeatedField<string> artist_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> Artist {
    get { return artist_; }
  }

  /// <summary>Field number for the "angajat" field.</summary>
  public const int AngajatFieldNumber = 7;
  private global::Angajat angajat_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Angajat Angajat {
    get { return angajat_; }
    set {
      angajat_ = value;
    }
  }

  /// <summary>Field number for the "filteredByDate" field.</summary>
  public const int FilteredByDateFieldNumber = 9;
  private bool filteredByDate_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool FilteredByDate {
    get { return filteredByDate_; }
    set {
      filteredByDate_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FestivalResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FestivalResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Bilet, other.Bilet)) return false;
    if (ResponseType != other.ResponseType) return false;
    if (!object.Equals(Spectacol, other.Spectacol)) return false;
    if (Message != other.Message) return false;
    if(!spectacole_.Equals(other.spectacole_)) return false;
    if (Error != other.Error) return false;
    if(!artist_.Equals(other.artist_)) return false;
    if (!object.Equals(Angajat, other.Angajat)) return false;
    if (FilteredByDate != other.FilteredByDate) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (bilet_ != null) hash ^= Bilet.GetHashCode();
    if (ResponseType != global::FestivalResponse.Types.ResponseType.Ok) hash ^= ResponseType.GetHashCode();
    if (spectacol_ != null) hash ^= Spectacol.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    hash ^= spectacole_.GetHashCode();
    if (Error.Length != 0) hash ^= Error.GetHashCode();
    hash ^= artist_.GetHashCode();
    if (angajat_ != null) hash ^= Angajat.GetHashCode();
    if (FilteredByDate != false) hash ^= FilteredByDate.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ResponseType != global::FestivalResponse.Types.ResponseType.Ok) {
      output.WriteRawTag(8);
      output.WriteEnum((int) ResponseType);
    }
    if (spectacol_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Spectacol);
    }
    spectacole_.WriteTo(output, _repeated_spectacole_codec);
    if (Error.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Error);
    }
    artist_.WriteTo(output, _repeated_artist_codec);
    if (Message.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Message);
    }
    if (angajat_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(Angajat);
    }
    if (bilet_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Bilet);
    }
    if (FilteredByDate != false) {
      output.WriteRawTag(72);
      output.WriteBool(FilteredByDate);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ResponseType != global::FestivalResponse.Types.ResponseType.Ok) {
      output.WriteRawTag(8);
      output.WriteEnum((int) ResponseType);
    }
    if (spectacol_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Spectacol);
    }
    spectacole_.WriteTo(ref output, _repeated_spectacole_codec);
    if (Error.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Error);
    }
    artist_.WriteTo(ref output, _repeated_artist_codec);
    if (Message.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Message);
    }
    if (angajat_ != null) {
      output.WriteRawTag(58);
      output.WriteMessage(Angajat);
    }
    if (bilet_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Bilet);
    }
    if (FilteredByDate != false) {
      output.WriteRawTag(72);
      output.WriteBool(FilteredByDate);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (bilet_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
    }
    if (ResponseType != global::FestivalResponse.Types.ResponseType.Ok) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseType);
    }
    if (spectacol_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spectacol);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    size += spectacole_.CalculateSize(_repeated_spectacole_codec);
    if (Error.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
    }
    size += artist_.CalculateSize(_repeated_artist_codec);
    if (angajat_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
    }
    if (FilteredByDate != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FestivalResponse other) {
    if (other == null) {
      return;
    }
    if (other.bilet_ != null) {
      if (bilet_ == null) {
        Bilet = new global::Bilet();
      }
      Bilet.MergeFrom(other.Bilet);
    }
    if (other.ResponseType != global::FestivalResponse.Types.ResponseType.Ok) {
      ResponseType = other.ResponseType;
    }
    if (other.spectacol_ != null) {
      if (spectacol_ == null) {
        Spectacol = new global::SpectacolDTO();
      }
      Spectacol.MergeFrom(other.Spectacol);
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    spectacole_.Add(other.spectacole_);
    if (other.Error.Length != 0) {
      Error = other.Error;
    }
    artist_.Add(other.artist_);
    if (other.angajat_ != null) {
      if (angajat_ == null) {
        Angajat = new global::Angajat();
      }
      Angajat.MergeFrom(other.Angajat);
    }
    if (other.FilteredByDate != false) {
      FilteredByDate = other.FilteredByDate;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ResponseType = (global::FestivalResponse.Types.ResponseType) input.ReadEnum();
          break;
        }
        case 18: {
          if (spectacol_ == null) {
            Spectacol = new global::SpectacolDTO();
          }
          input.ReadMessage(Spectacol);
          break;
        }
        case 26: {
          spectacole_.AddEntriesFrom(input, _repeated_spectacole_codec);
          break;
        }
        case 34: {
          Error = input.ReadString();
          break;
        }
        case 42: {
          artist_.AddEntriesFrom(input, _repeated_artist_codec);
          break;
        }
        case 50: {
          Message = input.ReadString();
          break;
        }
        case 58: {
          if (angajat_ == null) {
            Angajat = new global::Angajat();
          }
          input.ReadMessage(Angajat);
          break;
        }
        case 66: {
          if (bilet_ == null) {
            Bilet = new global::Bilet();
          }
          input.ReadMessage(Bilet);
          break;
        }
        case 72: {
          FilteredByDate = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ResponseType = (global::FestivalResponse.Types.ResponseType) input.ReadEnum();
          break;
        }
        case 18: {
          if (spectacol_ == null) {
            Spectacol = new global::SpectacolDTO();
          }
          input.ReadMessage(Spectacol);
          break;
        }
        case 26: {
          spectacole_.AddEntriesFrom(ref input, _repeated_spectacole_codec);
          break;
        }
        case 34: {
          Error = input.ReadString();
          break;
        }
        case 42: {
          artist_.AddEntriesFrom(ref input, _repeated_artist_codec);
          break;
        }
        case 50: {
          Message = input.ReadString();
          break;
        }
        case 58: {
          if (angajat_ == null) {
            Angajat = new global::Angajat();
          }
          input.ReadMessage(Angajat);
          break;
        }
        case 66: {
          if (bilet_ == null) {
            Bilet = new global::Bilet();
          }
          input.ReadMessage(Bilet);
          break;
        }
        case 72: {
          FilteredByDate = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the FestivalResponse message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum ResponseType {
      [pbr::OriginalName("OK")] Ok = 0,
      [pbr::OriginalName("ERROR")] Error = 1,
      [pbr::OriginalName("GOT_FESTIVAL_UPDATED")] GotFestivalUpdated = 2,
      [pbr::OriginalName("GET_FESTIVAL_LIST")] GetFestivalList = 3,
      [pbr::OriginalName("GOT_FESTIVAL_LIST_UPDATED")] GotFestivalListUpdated = 4,
      [pbr::OriginalName("USER_LOGGED_IN")] UserLoggedIn = 5,
      [pbr::OriginalName("USER_LOGGED_OUT")] UserLoggedOut = 6,
      [pbr::OriginalName("GET_ARTISTI")] GetArtisti = 7,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
